server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:ssl/keystore.p12"
    key-store-password: "togeball"
    key-store-type: "PKCS12"

spring:
  data:
    mongodb:
      uri: mongodb://i10a610.p.ssafy.io:27017/togeball_chat_3
  rabbitmq:
    host: i10a610.p.ssafy.io
    port: 4672
    username: ssafy
    password: ssafy
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: togeball-bucket
  servlet:
    multipart:
      max-file-size: 100MB
  config:
    import: optional:env/s3.yml

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
    io:
      awspring:
        cloud: DEBUG

websocket:
  relay:
    host: i10a610.p.ssafy.io
    port: 61613
    client:
      login: ssafy
      passcode: ssafy
    system:
      login: ssafy
      passcode: ssafy

rabbitmq:
  host: i10a610.p.ssafy.io
  port: 4672
  username: ssafy
  password: ssafy
  exchange:
    name: togeball.exchange
  queue:
    name: chat.queue
  routing-key: togeball.chat