server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8083
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:ssl/keystore.p12"
    key-store-password: "togeball"
    key-store-type: "PKCS12"

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
