server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:ssl/keystore.p12"
    key-store-password: "togeball"
    key-store-type: "PKCS12"

spring:
  data:
    redis:
      host: i10a610.p.ssafy.io
      port: 6379
      password: togeball

rabbitmq:
  host: i10a610.p.ssafy.io
  port: 4672
  username: ssafy
  password: ssafy
  exchange: togeball.exchange
  matching:
    queue: matching.queue
    routing-key: togeball.matching
